/**
 * The row shapes the data layer returns, and the errors it raises.
 *
 * ── Why these types are written here rather than generated ────────────────
 *
 * `src/types/database.ts` is generated by `npm run db:types` from the live
 * Supabase project, and that generator does not point at RDS. So the RDS-side
 * shapes are hand-written, transcribed from `services/api/migrations/0001_schema.sql`.
 *
 * That is a real loss and it is worth naming: until P9, a column added to a
 * migration and forgotten in the types was a compile error. Now it is a runtime
 * `undefined`. The compensating discipline is that this file sits next to the
 * migrations it mirrors — the reason task 3 put the schema in `services/api/`
 * rather than `infra/` — so a column added in one is a file away from the type
 * that has to change.
 *
 * The client keeps using the generated `Database` types for its own row shapes
 * (task 8 keeps the hook signatures identical), and these are the server's copy
 * of the same thing. Where they must agree, they agree by transcription, not by
 * a checked guarantee.
 *
 * ── The two sides now legitimately disagree about `card_status` ───────────
 *
 * P10's migration 0003 removed `'draft'` from `card_status` **on RDS only**.
 * `src/types/database.ts` is generated from the live Supabase project, which
 * still has that value and still serves /progress and generation until Phase F,
 * so the generated file will keep reporting four members while this file
 * declares three.
 *
 * **That is expected, and it is not fixed by hand-editing the generated file.**
 * For anything the API serves, this file is authoritative; the generated types
 * stay authoritative for the Supabase-backed paths until Phase F retires them.
 * `npm run db:types` will keep producing `'draft'` and should not be
 * interpreted as drift to correct.
 */

export type CardKind = 'basic' | 'cloze' | 'mcq';
/**
 * No `'draft'`. P10 removed it: drafts live in DynamoDB until the review gate
 * accepts them, so no row is ever written with that status (migration 0003).
 *
 * `DeckStatus` below keeps its own `'draft'`, which is a different thing --
 * "generation finished, the gate has not been passed" -- and is still reachable.
 */
export type CardStatus = 'active' | 'suspended' | 'archived';
export type FsrsState = 'new' | 'learning' | 'review' | 'relearning';
export type DeckStatus = 'generating' | 'draft' | 'active' | 'failed';
export type GenSource = 'text' | 'document' | 'manual';

export interface ProfileRow {
  id: string;
  display_name: string | null;
  timezone: string;
  daily_new_limit: number;
  fsrs_params: unknown | null;
  created_at: string;
  updated_at: string;
}

export interface DeckRow {
  id: string;
  user_id: string;
  title: string;
  description: string | null;
  status: DeckStatus;
  source: GenSource;
  new_cards_per_day: number;
  created_at: string;
  updated_at: string;
}

export interface CardRow {
  id: string;
  user_id: string;
  deck_id: string;
  kind: CardKind;
  payload: unknown;
  status: CardStatus;
  source_excerpt: string | null;
  /**
   * The topic this card is filed under, or null (P10 task 7, D11).
   *
   * Null is an ordinary state rather than missing data: hand-made cards have no
   * topic, every card predating migration 0004 has none, and a chunk whose
   * model output named no topic still produces perfectly good cards.
   */
  topic_id: string | null;
  fsrs_state: FsrsState;
  stability: number | null;
  difficulty: number | null;
  due: string;
  last_review: string | null;
  reps: number;
  lapses: number;
  scheduled_days: number;
  elapsed_days: number;
  learning_steps: number;
  created_at: string;
  updated_at: string;
}

export interface ReviewRow {
  id: string;
  user_id: string;
  card_id: string;
  rating: number;
  reviewed_at: string;
  duration_ms: number | null;
  state_before: FsrsState;
  stability_before: number | null;
  difficulty_before: number | null;
  elapsed_days: number;
  scheduled_days: number;
  due_before: string;
  last_review_before: string | null;
  elapsed_days_before: number;
  learning_steps_before: number;
  undone_at: string | null;
  state_after: FsrsState;
  stability_after: number | null;
  difficulty_after: number | null;
}

/**
 * The scheduling columns `review_card` accepts as `p_next`, and the only
 * columns a rating may change. Exactly what `src/lib/fsrs.ts` produces.
 */
export interface SchedulingUpdate {
  fsrs_state: FsrsState;
  stability: number | null;
  difficulty: number | null;
  due: string;
  last_review: string | null;
  scheduled_days: number;
  elapsed_days: number;
  learning_steps: number;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/**
 * The error codes the RPCs raise, kept from the Supabase originals so the
 * client keeps matching on the same strings.
 *
 * These were PostgREST's convention — a `PTxxx` SQLSTATE became HTTP status
 * xxx, automatically. There is no PostgREST here, so `services/api/src/lib/http.ts`
 * does that mapping explicitly. The codes did not change; what changed is that
 * something has to translate them on purpose.
 */
export const PG_ERROR = {
  /** Not found — **or not yours**. Deliberately the same answer. */
  notFound: 'PT404',
  /** The card moved since it was shown: two tabs rating the same card. */
  staleCard: 'PT409',
  /** An attempt to rewrite the append-only part of the review log. */
  appendOnly: 'PT403',
  /** Malformed input, raised by the RPCs' own validation. */
  invalidInput: '22023',
} as const;

/**
 * An error the API knows how to turn into a status code.
 *
 * Anything else that escapes the data layer is a 500, deliberately: an
 * unrecognised failure is a bug, and mapping it to a friendly 4xx would hide it.
 */
export class ApiError extends Error {
  readonly status: number;
  readonly code: string | undefined;

  /**
   * Fields are declared and assigned explicitly rather than written as
   * TypeScript *parameter properties* (`constructor(readonly status: number)`).
   *
   * That shorthand is one of the few constructs Node's `--experimental-strip-types`
   * refuses — it erases types but will not *generate* the assignments a parameter
   * property implies, and fails with ERR_UNSUPPORTED_TYPESCRIPT_SYNTAX. The
   * Lambda bundle would not care, because esbuild transpiles properly; local
   * execution does, and running this code against a local Postgres is how the
   * data layer gets exercised at all before RDS is deployed.
   *
   * Same family of constraint as the `enum` ban in `infra/` (see the header of
   * `infra/lib/config.ts`), and worth the four extra lines for the same reason:
   * the code stays runnable by the plain Node that is already installed.
   */
  constructor(status: number, message: string, code?: string) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.code = code;
  }
}

/**
 * The 404 every ownership check raises.
 *
 * **Never a 403.** A 403 confirms the id exists, which turns a card id into an
 * oracle for whether some other user owns a given uuid. RLS used to make "not
 * found" and "not yours" indistinguishable for free; here they are made
 * indistinguishable on purpose, and P9's acceptance criterion 5 checks for
 * exactly this.
 */
export function notFound(what: string): ApiError {
  return new ApiError(404, `${what} not found.`, PG_ERROR.notFound);
}

/** A Postgres error's SQLSTATE, if this is a Postgres error at all. */
export function pgErrorCode(error: unknown): string | undefined {
  const code = (error as { code?: unknown } | null)?.code;
  return typeof code === 'string' ? code : undefined;
}

/**
 * A topic. P10 task 7, D11.
 *
 * `slug` is the match key -- `name` normalised -- and is written only by
 * `data/topics.ts`. It never comes from a client and is never displayed;
 * `name` is the display form the model produced.
 */
export interface TopicRow {
  id: string;
  user_id: string;
  name: string;
  slug: string;
  created_at: string;
  updated_at: string;
}
