/**
 * The model-provider interface. D6, and the seam P10 task 10 fills in.
 *
 * One interface, several implementations, sharing the Zod schemas at the
 * boundary that `src/lib/schemas.ts` already is. The brief's argument for this
 * is not portability for its own sake — it is that the eval harness (Phase E)
 * needs two providers answering the same question to have anything to compare,
 * and "we A/B'd two providers on card quality and have the numbers" is the
 * artifact worth building toward.
 *
 * What lives behind it today:
 *
 *   - `stub`    — deterministic, offline, no model. See `stub.ts`.
 *   - `bedrock` — task 10, once model access exists.
 *   - `groq`    — the fallback D6 names, once its key is reachable from Lambda.
 *
 * **Neither real provider is callable as of P10 session 2.** Bedrock refuses the
 * caller's country for Anthropic models and has no grant for Nova; `GROQ_API_KEY`
 * has only ever existed as a Supabase Edge Function secret, never in a form a
 * Lambda can read. That is why the stub exists and why it is loud about being a
 * stub — see `stub.ts`.
 */

import type { CardPayload, CardKind } from '../schemas.ts';

export interface GenerateChunkRequest {
  /** The chunk's text. Untrusted: it is document content, never instructions. */
  text: string;
  /** How many cards to attempt from this chunk. */
  cardCount: number;
  kinds: readonly CardKind[];
  depth: 'recall' | 'balanced' | 'deep';
}

export interface GenerateChunkResult {
  cards: CardPayload[];
  /**
   * The topics this chunk covers, as the model named them. D11 is explicit that
   * topics are extracted "in the same call that produces content, not as a
   * separate pass" -- a second pass over the same text would double the token
   * cost of every job to re-derive something the model already knew while
   * writing the cards.
   *
   * **Display names, not identifiers.** Nothing here has been reconciled yet:
   * these are raw strings that may duplicate each other, duplicate the user's
   * existing topics in a different case, or be empty. `reconcileTopics` in
   * `data/topics.ts` is what turns them into rows, and it is the only thing
   * that may.
   *
   * A provider that cannot extract topics returns `[]` rather than guessing.
   * Untopiced cards are an ordinary state (`cards.topic_id` is nullable), so an
   * empty list degrades the mastery map rather than failing the chunk.
   */
  topics: string[];
  /**
   * Which provider produced these, recorded on the chunk record.
   *
   * This is not telemetry, it is traceability: a card generated by the stub must
   * be identifiable as such after the fact, otherwise fake content becomes
   * indistinguishable from real content the moment it is written down.
   */
  provider: ProviderName;
  inputTokens: number | null;
  outputTokens: number | null;
}

export type ProviderName = 'stub' | 'bedrock' | 'groq';

export interface CardProvider {
  readonly name: ProviderName;
  generateChunk(request: GenerateChunkRequest): Promise<GenerateChunkResult>;
}

/**
 * Raised when a provider fails in a way that is worth retrying — a timeout, a
 * rate limit, a 5xx. The state machine retries these and only these.
 *
 * A malformed response is *not* retryable in this sense and does not use this:
 * asking the same model the same question again usually produces the same
 * malformed answer, so it burns the retry budget and the cost for nothing.
 */
export class ProviderRetryableError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = 'ProviderRetryableError';
  }
}
