/**
 * The model-provider interface. D6, and the seam P10 task 10 fills in.
 *
 * One interface, several implementations, sharing the Zod schemas at the
 * boundary that `src/lib/schemas.ts` already is. The brief's argument for this
 * is not portability for its own sake — it is that the eval harness (Phase E)
 * needs two providers answering the same question to have anything to compare,
 * and "we A/B'd two providers on card quality and have the numbers" is the
 * artifact worth building toward.
 *
 * What lives behind it today:
 *
 *   - `stub`    — deterministic, offline, no model. See `stub.ts`.
 *   - `groq`    — **a real model, callable today.** See `groq.ts`.
 *   - `bedrock` — still unimplemented; model access has not been granted.
 *
 * **This changed at DS1.** Through all of P10 neither real provider was
 * callable — Bedrock refused the caller's country for Anthropic models and had
 * no grant for Nova, and `GROQ_API_KEY` existed only as a Supabase Edge Function
 * secret that no Lambda could read. Groq now runs against the API directly with
 * the key in the server environment, so the stub is no longer the only
 * implementation that works. It is kept, and kept loud about being a stub,
 * because a real provider does not make a fake one safer.
 */

import type { CardPayload, CardKind } from '../schemas.ts';

export interface GenerateChunkRequest {
  /** The chunk's text. Untrusted: it is document content, never instructions. */
  text: string;
  /** How many cards to attempt from this chunk. */
  cardCount: number;
  kinds: readonly CardKind[];
  depth: 'recall' | 'balanced' | 'deep';
}

export interface GenerateChunkResult {
  cards: CardPayload[];
  /**
   * The topics this chunk covers, as the model named them. D11 is explicit that
   * topics are extracted "in the same call that produces content, not as a
   * separate pass" -- a second pass over the same text would double the token
   * cost of every job to re-derive something the model already knew while
   * writing the cards.
   *
   * **Display names, not identifiers.** Nothing here has been reconciled yet:
   * these are raw strings that may duplicate each other, duplicate the user's
   * existing topics in a different case, or be empty. `reconcileTopics` in
   * `data/topics.ts` is what turns them into rows, and it is the only thing
   * that may.
   *
   * A provider that cannot extract topics returns `[]` rather than guessing.
   * Untopiced cards are an ordinary state (`cards.topic_id` is nullable), so an
   * empty list degrades the mastery map rather than failing the chunk.
   */
  topics: string[];
  /**
   * Which provider produced these, recorded on the chunk record.
   *
   * This is not telemetry, it is traceability: a card generated by the stub must
   * be identifiable as such after the fact, otherwise fake content becomes
   * indistinguishable from real content the moment it is written down.
   */
  provider: ProviderName;
  inputTokens: number | null;
  outputTokens: number | null;
}

export type ProviderName = 'stub' | 'bedrock' | 'groq';

export interface CardProvider {
  readonly name: ProviderName;
  generateChunk(request: GenerateChunkRequest): Promise<GenerateChunkResult>;
}

/**
 * Raised when a provider fails in a way that is worth retrying — a timeout, a
 * rate limit, a 5xx. The state machine retries these and only these.
 *
 * A malformed response is *not* retryable in this sense and does not use this:
 * asking the same model the same question again usually produces the same
 * malformed answer, so it burns the retry budget and the cost for nothing.
 */
export class ProviderRetryableError extends Error {
  /**
   * How long the provider asked us to wait, in milliseconds, when it said so.
   *
   * Added at DS1, and it earned itself immediately. Groq's free tier limits
   * **tokens per minute**, so a 429 there clears in tens of seconds rather than
   * the hundreds of milliseconds an exponential backoff assumes — DS1's first
   * multi-chunk run lost two chunks of four to retries that all landed inside
   * one still-exhausted window.
   *
   * The server knows when it will next accept work and says so in `retry-after`.
   * Guessing when the answer is available is how a bounded retry policy becomes
   * a policy that reliably fails. `undefined` means the provider did not say,
   * and the runner falls back to its own backoff.
   */
  readonly retryAfterMs: number | undefined;

  constructor(message: string, options?: { cause?: unknown; retryAfterMs?: number }) {
    super(message, { cause: options?.cause });
    this.name = 'ProviderRetryableError';
    this.retryAfterMs = options?.retryAfterMs;
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * ANSWERING. DS2 task 6, and a deliberately separate interface.
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Grounded chat needs a chat completion, and `CardProvider` above is already a
 * chat client. The obvious move was to add `answer()` to it. That was rejected,
 * and the reason is a safety property rather than a taste in interfaces:
 *
 *   **`StubProvider` implements `CardProvider`.** Adding `answer()` to that
 *   interface obliges the stub to implement it — and a stub answer is the one
 *   thing DS2 §3 forbids outright. A stub *card* announces itself in its own
 *   text and passes a review gate before it becomes anything; a stub *answer* is
 *   fluent prose about the reader's own study material with no gate in front of
 *   it, and nothing on screen says it is fake.
 *
 * So answering is a second, narrower interface that a provider may or may not
 * implement, and `StubProvider` does not. That is not a convention: it is the
 * type system. `resolveAnsweringProvider()` returns one only if the configured
 * provider actually has the capability, so `CARD_PROVIDER=stub` makes the chat
 * endpoint refuse rather than answer — which is the correct behaviour, since a
 * deployment with no real model has nothing honest to say.
 *
 * `BedrockProvider` will implement both when model access is granted. Nothing
 * about this shape prevents that; it prevents only the stub from acquiring a
 * capability it must not have.
 */

export interface AnswerRequest {
  /** The user's question, verbatim. */
  question: string;
  /**
   * The retrieved passages, in rank order, as text.
   *
   * **Untrusted.** They are the user's own documents, but that user pasted them
   * from somewhere: material to answer *about*, never instructions to follow.
   * `prompt.ts` delimits them and repeats the rule after them, which is where
   * the ordering argument in that file matters most.
   */
  passages: string[];
}

export interface AnswerResult {
  /** The answer text, or the model's own statement that it cannot answer. */
  answer: string;
  /**
   * Whether the model claims it answered from the passages.
   *
   * **A claim, not a proof, and the handler treats it as one.** A model that
   * answered from pretraining and set this to `true` is not detectable here —
   * nothing in this codebase verifies groundedness, and DS2 §7 says so. What
   * this buys is the honest case: a model that knows it could not answer says
   * so, and the pane renders that as the first-class outcome it is rather than
   * as an error.
   */
  grounded: boolean;
  /**
   * Which passages the model cited, as 1-based indices into `passages`.
   *
   * Parsed out of the answer text by the provider. Indices outside the range
   * are dropped rather than trusted: a `[7]` in a five-passage prompt is a
   * hallucination, and it is detectable precisely because the model was never
   * shown an id it could invent a plausible version of.
   */
  citations: number[];
  provider: ProviderName;
  inputTokens: number | null;
  outputTokens: number | null;
}

/**
 * A provider that can answer a question from passages.
 *
 * Deliberately not extended by `CardProvider`. See the block comment above —
 * the separation is what stops `StubProvider` from being obliged to answer.
 */
export interface AnsweringProvider {
  readonly name: ProviderName;
  answer(request: AnswerRequest): Promise<AnswerResult>;
}
